export const activities = [
  {
    id: "1",
    title: "Deep Breathing",
    description: "Take 10 deep breaths, inhaling through your nose and exhaling through your mouth.",
    duration: "2 minutes",
    icon: "wind",
  },
  {
    id: "2",
    title: "Quick Walk",
    description: "Go for a brisk 10-minute walk to clear your mind and reduce cravings.",
    duration: "10 minutes",
    icon: "footprints",
  },
  {
    id: "3",
    title: "Drink Water",
    description: "Drink a full glass of water slowly, focusing on the sensation.",
    duration: "3 minutes",
    icon: "glass-water",
  },
  {
    id: "4",
    title: "Stretch Break",
    description: "Do some simple stretches to release tension in your body.",
    duration: "5 minutes",
    icon: "stretching",
  },
  {
    id: "5",
    title: "Call a Friend",
    description: "Reach out to a supportive friend or family member for a quick chat.",
    duration: "10 minutes",
    icon: "phone",
  },
  {
    id: "6",
    title: "Mindfulness Moment",
    description: "Focus on your surroundings and name 5 things you can see, 4 things you can touch, 3 things you can hear, 2 things you can smell, and 1 thing you can taste.",
    duration: "5 minutes",
    icon: "brain",
  },
  {
    id: "7",
    title: "Healthy Snack",
    description: "Eat a piece of fruit or a small healthy snack to distract your mouth and hands.",
    duration: "5 minutes",
    icon: "apple",
  },
  {
    id: "8",
    title: "Journal",
    description: "Write down your feelings about the craving and why you want to quit smoking.",
    duration: "7 minutes",
    icon: "pen-line",
  },
  {
    id: "9",
    title: "Quick Cleaning",
    description: "Clean or organize a small area of your home to keep your hands busy.",
    duration: "10 minutes",
    icon: "spray-can",
  },
  {
    id: "10",
    title: "Listen to Music",
    description: "Play an upbeat song and focus on the rhythm and lyrics.",
    duration: "4 minutes",
    icon: "music",
  },
];