export const smokingFacts = [
  "Smoking causes more than 480,000 deaths each year in the United States alone.",
  "Tobacco smoke contains more than 7,000 chemicals, including at least 70 known to cause cancer.",
  "Smoking is the leading cause of preventable death worldwide.",
  "Secondhand smoke exposure causes nearly 41,000 deaths among nonsmoking adults each year.",
  "Smokers are more likely to develop heart disease, stroke, and lung cancer than nonsmokers.",
  "Smoking causes about 90% of all lung cancer deaths in men and women.",
  "Smoking causes about 80% of all deaths from chronic obstructive pulmonary disease (COPD).",
  "Life expectancy for smokers is at least 10 years shorter than for nonsmokers.",
  "Quitting smoking before the age of 40 reduces the risk of dying from smoking-related diseases by about 90%.",
  "Within 20 minutes of quitting, your heart rate and blood pressure drop.",
  "Within 12 hours of quitting, the carbon monoxide level in your blood drops to normal.",
  "Within 2-12 weeks of quitting, your circulation improves and your lung function increases.",
  "After 1 year of quitting, your risk of coronary heart disease is about half that of a smoker's.",
  "After 5 years of quitting, your risk of mouth, throat, esophagus, and bladder cancer is cut in half.",
  "After 10 years of quitting, your risk of lung cancer falls to about half that of a smoker's.",
  "The average smoker tries to quit 30 times before successfully quitting for good.",
  "Nicotine reaches the brain within 10 seconds of inhalation.",
  "Cigarette butts are the most littered item in the world, with an estimated 4.5 trillion discarded annually.",
  "The financial cost of smoking is substantial - a pack-a-day smoker spends thousands of dollars per year on cigarettes.",
  "Smoking affects the immune system, making smokers more susceptible to infections.",
];